# We do not use drafter to actually publish release,
# so this is just a sane default to easy manual touch ups.
name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
template: |
  ## âœ¨ Highlights

  <!-- Add release highlights here manually -->

  ## ðŸ“‹ Changelog

  $CHANGES

  ## ðŸ‘¥ Contributors

  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

# Use compatible markdown, so we could also pull the resulting
# text into a unified CHANGELOG.md
change-template: '- $TITLE [#$NUMBER]($URL)'
change-title-escapes: '\<*_&#@`' # You can add # and @ here if needed

categories:
  - title: 'ðŸ’¥ Breaking'
    label: 'breaking'
  - title: 'ðŸš€ New'
    labels:
      - 'enhancement'
      - 'ux'
  - title: 'ðŸ› Fixed'
    labels:
      - 'bug'
      - 'bug third party'
  - title: 'ðŸ”’ Security'
    labels:
      - 'security'
  - title: 'ðŸ”§ Maintenance'
    labels:
      - 'refactor'
    collapse-after: 3
  - title: 'ðŸ“š Documentation'
    labels:
      - 'documentation'

exclude-labels:
  - 'skip-changelog'
  - 'chore'
  - 'infra'
