export const LOCAL_STORAGE_KEYS = {
  RUN_QUERY_BUTTON_VALUE: 'RUN_QUERY_BUTTON_VALUE',
  MAX_CONNECTION_POOL_SIZE: 'MAX_CONNECTION_POOL_SIZE',
  MAIN_LAYOUT_DIMENSIONS: 'MAIN_LAYOUT_DIMENSIONS',
  NAVBAR_LAYOUT_DIMENSIONS: 'NAVBAR_LAYOUT_DIMENSIONS',
  ONBOARDING_SHOWN: 'ONBOARDING_SHOWN',
};
