export const LOCAL_STORAGE_KEYS = {
  RUN_QUERY_BUTTON_VALUE: 'RUN_QUERY_BUTTON_VALUE',
  MAX_CONNECTION_POOL_SIZE: 'MAX_CONNECTION_POOL_SIZE',
  MAIN_LAYOUT_DIMENSIONS: 'MAIN_LAYOUT_DIMENSIONS',
  SIDEBAR_COLLAPSED: 'SIDEBAR_COLLAPSED',
  ONBOARDING_SHOWN: 'ONBOARDING_SHOWN',
  WHATS_NEW_VERSION_SHOWN: 'WHATS_NEW_VERSION_SHOWN',
  AI_SERVICE_CONFIG: 'AI_SERVICE_CONFIG',
  BROWSER_COMPATIBILITY_DISMISSED: 'BROWSER_COMPATIBILITY_DISMISSED',
  CORS_PROXY_SETTINGS: 'CORS_PROXY_SETTINGS',
  HTTPSERVER_CREDENTIALS: 'HTTPSERVER_CREDENTIALS',
};

export const SESSION_STORAGE_KEYS = {
  FALLBACK_MODE_WARNING_SHOWN: 'FALLBACK_MODE_WARNING_SHOWN',
};
