name: Deploy to Cloudflare Pages

on:
  workflow_run:
    workflows: ['Lint, Build & Test']
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v9
        with:
          name: build
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          path: dist
          if_no_artifact_found: fail

      - name: Determine branch name
        id: branch-name
        run: |
          if [ "${{ github.event.workflow_run.event }}" == "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=pondpilot --branch=${{ steps.branch-name.outputs.branch }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} # Enable GitHub Deployments

