name: Update PR with test results

on:
  workflow_run:
    workflows: ['Lint, Build & Test']
    types:
      - completed

# Privileged access to the repository
permissions:
  checks: write

jobs:
  get_workflow_conclusion:
    if: github.event.workflow_run.event == 'pull_request'
    name: Lookup Conclusion of Workflow_Run Event
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.get_conclusion.outputs.result }}
    steps:
      - name: Get Workflow Run
        uses: actions/github-script@v7
        id: get_conclusion
        with:
          script: |
            const response = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            
            return response.data.conclusion;
          result-encoding: string

  update-pr:
    name: Update PR with test results
    runs-on: ubuntu-latest
    needs: get_workflow_conclusion
    if: >
      github.event.workflow_run.event == 'pull_request' 
      && needs.get_workflow_conclusion.outputs.conclusion == 'success'

    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v9
        with:
          name: playwright-report
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          path: playwright-report
          if_no_artifact_found: fail
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: 'playwright-report/results.xml'
          check_name: 'Integration Tests'
